### ISSUE TITLE
assumes .kube directory exists

### ISSUE THREAD

**Issue by walidshaari** [DavidZisky/60sk3s#10]
will submit a pull request to fix this and test if .kube not found, create it

**Comment by DavidZisky** [comment]
Thank for this as well, but again - I don't want to create .kube folder because for some use cases you use kubeconfig directly or by reference to it. I agree that some checks could be added in a current script but don't create .kube as it's the job of kubectl. I'll keep that one open to have a conversation what's best.

**Comment by walidshaari** [comment]
sure, will remove it from my local branch. it makes sense what you say, as the main use case is rapid testing
