### ISSUE TITLE
Add SET Buitlin to each bash script

### ISSUE THREAD

**Issue by Exadra37** [DavidZisky/60sk3s#4]
His there any special reason for the current bash scripts do not use [The Set Builtin](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html#The-Set-Builtin) options to make them safe to run?

I would use at least as:

```
#!/bin/bash
set -eu
```

**Comment by DavidZisky** [comment]
Fair enough. This script started as just few lines to automate part of the process and then evolved. That's why it does not follow some of the best practices. Recently I've been busy working on DO version so also didn't pay too much attention to clean it up yet. But you're definitely right, I'll add it. Thanks

**Comment by Exadra37** [comment]
Thanks for adding the `set -e` :).

Any special reason to left out the `-u` flag?

This flag saved me already a lot of times, like `rm -rf ~/${SOME_PATH}`, because if `${SOME_PATH}` is empty we will delete the entire home directory, but with the `-u` flag set the bash script will exit with an error. This is only an example to illustrate why I think its very important to use the `-u` flag.

**Comment by DavidZisky** [comment]
Yes, I know what's set -u is for and yes, there is a reason to not use it. As explained in PR:

"Tested, set -u can't be used due to specific way the script works (for example it waits for the IP addresses for VMs being assigned so at the beginning variable will be empty, but there are checks built into the script. I'll also add more"

To be more precise - some vars here gonna be empty at the beginning by design, but script itself does the checks to prevent situations like one you mentioned. For example:

```
DEFAULT_PROJECT=`gcloud config list --format 'value(core.project)'`
DEFAULT_ZONE=`gcloud config list --format 'value(compute.zone)'`
ZONE="${DEFAULT_ZONE:-$ZONE}"
PROJECT="${DEFAULT_PROJECT:-$PROJECT}"
```

if default project and zone are not set via gcloud then these vars will be empty but in such case script set them to defaults I put.
