### ISSUE TITLE
Using an .env file instead of hardcoded TOKEN in many files

### ISSUE THREAD

**Issue by pascalandy** [DavidZisky/60sk3s#6]
Hi,
Your project is very cool!

Would you consider to use a ".env" file that contains all the variables mentioned in the README (https://github.com/DavidZisky/60sk3s/tree/do_ccm/digitalocean/cloud_manager)?

This could be improved:

- Add your DigitalOcean api token on line 7 in externaldns-values.yaml file
- Add your DigitalOcean api token on line 7 in k3s_deployer_cloudmanag.sh file
- Add your DigitalOcean api token on line 7 in dotoken.yaml file

I could do PR.
Cheers!

**Comment by DavidZisky** [comment]
Hi @pascalandy 

Yes, definitely, that's the way to go. It's POC for now (that's why it's not merged to master yet). I was focused until now on making all the pieces work together and this project evolved from my previous solution when DO token had to be put only in one place. But yeah, since the whole solution is working now, I'll focus on making it better, add some best practices, etc.

Thanks for checking :)

**Comment by pascalandy** [comment]
Great! Let me know if I can test something!

**Comment by DavidZisky** [comment]
@pascalandy implemented. Feel free to give it a try if you can.
