### ISSUE TITLE
kubectl not installed by default

### ISSUE THREAD

**Issue by walidshaari** [DavidZisky/60sk3s#9]
will create a pull request to install it, I already have it updated in the script, however, have other issue need to solve too

**Comment by DavidZisky** [comment]
Thanks a lot for the effort, but the point of this script was to have something as lightweight as possible - I don't want to add to many checks and dependencies in it. It's meant to be for people who use kubernetes on a daily basis and want an easy way to quickly spin up a test cluster. Therefore I assume people have kubectl installed. Another aspect is that I am using this script as a part of CI/CD where kubectl won't be available in first step but will be later so I don't want the script to fail because of lack of kubectl.
